package sara.ahmed.moatazsamir.main.pojo;

import java.util.ArrayList;

public class Orange extends Model{

    public Orange(String typeBundleName)
    {
        ArrayList<String> codeNumber = new ArrayList<>() ;
        ArrayList<String> codeDescription = new ArrayList<>() ;
        ArrayList<String> codeCategory = new ArrayList<>() ;
        ArrayList<String> separateCategories = new ArrayList<>() ;
        ArrayList<String> determineAction = new ArrayList<>() ;

        switch (typeBundleName)
        {
            case "ViewModelData":
                codeNumber.add("#101*1*");          codeDescription.add("تحويل رصيد");    codeCategory.add("codeCategory");    separateCategories.add("separateCategories");    determineAction.add("ACTION_DIAL");
                codeNumber.add("*");          codeDescription.add("تحويل رصيد");    codeCategory.add("codeCategory");    separateCategories.add("separateCategories");    determineAction.add("ACTION_DIAL");
                codeNumber.add("*0*#");          codeDescription.add("تحويل رصيد");    codeCategory.add("codeCategory");    separateCategories.add("separateCategories");    determineAction.add("ACTION_DIAL");
                break;

            case "ViewModelCodesDataConnectBundles":
                codeNumber.add("#222*24#");          codeDescription.add("[GO فيديو ماكس]\n" + "السعر: 35 جنية\n" + "رصيد الباقة: 4500 ميجابايت\n" + "صالحه لمده: 28 يوم");    codeCategory.add("باقات ميني GO");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*21#");          codeDescription.add("[GO فيديو اليومية]\n" + "السعر: 2 جنية\n" + "رصيد الباقة: 200 ميجابايت\n" + "صالحه لمده: يوم");    codeCategory.add("باقات ميني GO");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*23#");          codeDescription.add("[GO فيديو الشهرية]\n" + "السعر: 5 جنية\n" + "رصيد الباقة: 450 ميجابايت\n" + "صالحه لمده: 28 يوم");    codeCategory.add("باقات ميني GO");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*31#");          codeDescription.add("[GO Games اليومية]\n" + "السعر: 1 جنية\n" + "رصيد الباقة: 100 ميجابايت\n" + "صالحه لمده: 24 ساعة");    codeCategory.add("باقات ميني GO");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*32#");          codeDescription.add("[GO Games الاسبوعية]\n" + "السعر: 3 جنية\n" + "رصيد الباقة: 250 + 75 ميجابايت في الويك اند\n" + "صالحه لمده: 7 أيام");    codeCategory.add("باقات ميني GO");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*33#");          codeDescription.add("[GO Games الشهرية]\n" + "السعر: 10 جنية\n" + "رصيد الباقة: 1000 + 300 ميجابايت في الويك اند\n" + "صالحه لمده: 30 يوم");    codeCategory.add("باقات ميني GO");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*11#");          codeDescription.add("[GO سوشيال]\n" + "السعر: 1 جنية\n" + "رصيد الباقة: 100 ميجابايت\n" + "صالحه لمده: 24 ساعة");    codeCategory.add("باقات ميني GO");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*41#");          codeDescription.add("[GO from home]\n" + "السعر: 10 جنية\n" + "رصيد الباقة: 1000 ميجابايت\n" + "صالحه لمده: 28 يوم");    codeCategory.add("باقات ميني GO");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*42#");          codeDescription.add("[GO from home ماكس]\n" + "السعر: 35 جنية\n" + "رصيد الباقة: 4500 ميجابايت\n" + "صالحه لمده: 28 يوم");    codeCategory.add("باقات ميني GO");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");

                codeNumber.add("#222#");          codeDescription.add("[GO-Net 7.5]\n" + "السعر: 7.5 جنيه\n" + "سعة الباقة: 250 ميجا\n" + "\n" + "[GO-Net 15]\n" + "السعر: 15 جنيه\n" + "سعة الباقة: 750 ميجا\n" + "\n" + "[GO-Net 30]\n" + "السعر: 30 جنيه\n" + "سعة الباقة: 1800 ميجا\n" + "\n" + "[GO-Net 45]\n" + "السعر: 45 جنيه\n" + "سعة الباقة: 2,800 ميجا\n" + "\n" + "[GO-Net 60]\n" + "السعر: 60 جنيه\n" + "سعة الباقة: 4,250 ميجا\n" + "\n" + "[GO-Net 75]\n" + "السعر: 75 جنيه\n" + "سعة الباقة: 5,500 ميجا\n" + "\n" + "[GO-Net 100]\n" + "السعر: 100 جنيه\n" + "سعة الباقة: 9,000 ميجا\n" + "\n" + "[GO-Net 150]\n" + "السعر: 150 جنيه\n" + "سعة الباقة: 12,000 ميجا\n" + "\n" + "[GO-Net 250]\n" + "السعر: 250 جنيه\n" + "سعة الباقة: 20,000 ميجا\n" + "\n" + "[GO-Net 400]\n" + "السعر: 400 جنيه\n" + "سعة الباقة: 40,000 ميجا");    codeCategory.add("باقات GO-Net");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*9#");        codeDescription.add("يمكن تجديد باقة الانترنت في اي وقت مع ترحيل الميجابايتس المتبقية");    codeCategory.add("لتجديد باقات Go-Net");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#137#");          codeDescription.add("يمكن للعملاء خسارة ميزة ترحيل الميجابايتس المتبقية وتغيير صلاحية الباقة الي 30 يوم");    codeCategory.add("لغيير صلاحيه باقات Go-Net");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");

                codeNumber.add("#222*10#");          codeDescription.add("[GO 10]\n" + "السعر: 10 جنية\n" + "رصيد الباقة: 1,000 سوبرميجا\n" + "استخدام ما بعد الباقة: جنية 0.15 / ميجابايت");    codeCategory.add("GO سوبر");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*20#");          codeDescription.add("[GO 20]\n" + "السعر: 20 جنية\n" + "رصيد الباقة: 2,250 سوبرميجا\n" + "استخدام ما بعد الباقة: جنية 0.15 / ميجابايت");    codeCategory.add("GO سوبر");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*35#");          codeDescription.add("[GO 35]\n" + "السعر: 35 جنية\n" + "رصيد الباقة: 4,500 سوبرميجا\n" + "استخدام ما بعد الباقة: جنية 0.15 / ميجابايت");    codeCategory.add("GO سوبر");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*50#");          codeDescription.add("[GO 50]\n" + "السعر: 50 جنية\n" + "رصيد الباقة: 7,000 سوبرميجا\n" + "استخدام ما بعد الباقة: جنية 0.15 / ميجابايت");    codeCategory.add("GO سوبر");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*70#");          codeDescription.add("[GO 70]\n" + "السعر: 70 جنية\n" + "رصيد الباقة: 10,500 سوبرميجا\n" + "استخدام ما بعد الباقة: جنية 0.15 / ميجابايت");    codeCategory.add("GO سوبر");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*120#");         codeDescription.add("[GO 120]\n" + "السعر: 120 جنية\n" + "رصيد الباقة: 20,000 سوبرميجا\n" + "استخدام ما بعد الباقة: جنية 0.15 / ميجابايت");    codeCategory.add("GO سوبر");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#222*200#");         codeDescription.add("[GO 200]\n" + "السعر: 200 جنية\n" + "رصيد الباقة: 36,000 سوبرميجا\n" + "استخدام ما بعد الباقة: جنية 0.15 / ميجابايت");    codeCategory.add("GO سوبر");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
             //   codeNumber.add("#150*20#");          codeDescription.add("[الباقات الاضافية المتاحة]\n" + "2,250 سوبر ميجا ب 20 جنيه");    codeCategory.add("GO سوبر");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
              //  codeNumber.add("#150*30#");          codeDescription.add("[الباقات الاضافية المتاحة]\n" + "3,600 سوبر ميجا ب 30 جنيه");    codeCategory.add("GO سوبر");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");

                codeNumber.add("#433#1#");          codeDescription.add("[GO Sports اليومية]\n" + "السعر: 35 جنية\n" + "رصيد الباقة: 24 ساعه علي 3000MB + beIN Connect\n" + "باقة GO Sports اليومية لا تجدد تلقائيا و تجدد عند الطلب");    codeCategory.add("باقات Go Sports");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#433#2#");          codeDescription.add("[GO Sports الشهرية]\n" + "السعر: 130 جنية\n" + "رصيد الباقة: 30 يوم علي 7000MB + beIN Connect\n" + "باقة GO Sports الشهرية تجدد تلقائيا كل 30 يوم");    codeCategory.add("باقات Go Sports");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");

                codeNumber.add("#136#");          codeDescription.add("معرفة عدد الميجابايتس المتبقية");    codeCategory.add("اكواد مهمه");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#100#41#");          codeDescription.add("كود اشتراك جميع باقات الانترنت");    codeCategory.add("اكواد مهمه");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");

                codeNumber.add("https://www.orange.eg/ar/internet/go-super");    codeDescription.add("لمزيد من التفاصيل حول باقات GO سوبر");    codeCategory.add( "المصدر الرئيسي");    separateCategories.add("URLSource");    determineAction.add("ACTION_VIEW");
                codeNumber.add("https://www.orange.eg/ar/internet/go-net-packages");    codeDescription.add("لمزيد من التفاصيل حول باقات GO-Net");    codeCategory.add( "المصدر الرئيسي");    separateCategories.add("URLSource");    determineAction.add("ACTION_VIEW");
                codeNumber.add("https://www.orange.eg/ar/internet/go-mini");    codeDescription.add("لمزيد من التفاصيل حول باقات ميني GO");    codeCategory.add( "المصدر الرئيسي");    separateCategories.add("URLSource");    determineAction.add("ACTION_VIEW");
                codeNumber.add("https://www.orange.eg/ar/internet/go-sports-packages");    codeDescription.add("لمزيد من التفاصيل حول باقات Go Sports");    codeCategory.add( "المصدر الرئيسي");    separateCategories.add("URLSource");    determineAction.add("ACTION_VIEW");

                break;

            case "ViewModelCodesDataHekayaBundles":


                codeNumber.add("#0#5121#");          codeDescription.add("[الكينج 20] \n" + "الاشتراك الشهري: 20 جنيه \n" + "سوبر ميجابايتس اساسيه: 750\n" + "دقائق لاورنج للشبكات الاخري: 150");    codeCategory.add("أنظمة الكينج");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#0#5122#");          codeDescription.add("[الكينج 30] \n" + "الاشتراك الشهري: 30 جنيه\n" + "سوبر ميجابايتس اساسيه: 1400\n" + "دقائق لاورنج للشبكات الاخري: 250");    codeCategory.add("أنظمة الكينج");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#0#5123#");          codeDescription.add("[الكينج 40] \n" + "الاشتراك الشهري: 40 جنيه\n" + "سوبر ميجابايتس اساسيه: 2100\n" + "دقائق لاورنج للشبكات الاخري: 350");    codeCategory.add("أنظمة الكينج");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#0#5124#");          codeDescription.add("[الكينج 60] \n" + "الاشتراك الشهري: 60 جنيه\n" + "سوبر ميجابايتس اساسيه: 4000\n" + "دقائق لاورنج للشبكات الاخري: 500");    codeCategory.add("أنظمة الكينج");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");

                codeNumber.add("#0#5111#");          codeDescription.add("[كنترول 25] \n" + "الاشتراك الشهري (يخصم من الرصيد): 25 جنيه \n" + "وحدات (دقائق و ميجابايتس و رسائل): 900\n" + "بلس دقائق: 100\n" + "بلس سوشيال: تصل الي 1,800\n" + "وحدات (عرض ضعف الباقة للخطوط الجديدة): 1,800 (تصل الي 3,600 سوشيال ميجابايتس)");    codeCategory.add("باقات كنترول");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#0#5112#");          codeDescription.add("[كنترول 30] \n" + "الاشتراك الشهري (يخصم من الرصيد): 30جنيه \n" + "وحدات (دقائق و ميجابايتس و رسائل): 1200\n" + "بلس دقائق: 200\n" + "بلس سوشيال: تصل الي 2,400\n" + "وحدات (عرض ضعف الباقة للخطوط الجديدة): 2,400 (تصل الي 4,800 سوشيال ميجابايتس)");    codeCategory.add("باقات كنترول");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#0#5113#");          codeDescription.add("[كنترول 50] \n" + "الاشتراك الشهري (يخصم من الرصيد): 50جنيه \n" + "وحدات (دقائق و ميجابايتس و رسائل): 2250\n" + "بلس دقائق: 400\n" + "بلس سوشيال: 4500\n" + "عدد الأرقام الاضافية: 1 \n" + "دقائق المجموعة: 300\n" + "وحدات (عرض ضعف الباقة للخطوط الجديدة): 4,500 (تصل الي 9,000 سوشيال ميجابايتس)");    codeCategory.add("باقات كنترول");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#0#5114#");          codeDescription.add("[كنترول 70] \n" + "الاشتراك الشهري (يخصم من الرصيد): 70جنيه \n" + "وحدات (دقائق و ميجابايتس و رسائل): 3300\n" + "بلس دقائق: 600\n" + "بلس سوشيال: تصل الي 6,600\n" + "عدد الأرقام الاضافية: 1 \n" + "دقائق المجموعة: 300\n" + "وحدات (عرض ضعف الباقة للخطوط الجديدة): 6,600 (تصل الي 13,200 سوشيال ميجابايتس)");    codeCategory.add("باقات كنترول");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#0#5115#");          codeDescription.add("[كنترول 100] \n" + "الاشتراك الشهري (يخصم من الرصيد): 100جنيه \n" + "وحدات (دقائق و ميجابايتس و رسائل): 6000\n" + "بلس دقائق: 1200\n" + "بلس سوشيال: تصل الي 12,000\n" + "عدد الأرقام الاضافية: 2 \n" + "دقائق المجموعة: 450\n" + "وحدات (عرض ضعف الباقة للخطوط الجديدة): 12,000 (تصل الي 24,000 سوشيال ميجابايتس)");    codeCategory.add("باقات كنترول");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#0#5116#");          codeDescription.add("[كنترول 150] \n" + "الاشتراك الشهري (يخصم من الرصيد): 150جنيه \n" + "وحدات (دقائق و ميجابايتس و رسائل): 9600\n" + "بلس دقائق: 2700\n" + "بلس سوشيال: تصل الي 19,200\n" + "عدد الأرقام الاضافية: 3 \n" + "دقائق المجموعة: 600\n" + "وحدات (عرض ضعف الباقة للخطوط الجديدة): 19,200 (تصل الي 38,400 سوشيال ميجابايتس)");    codeCategory.add("باقات كنترول");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");

                codeNumber.add("#0#5131#");          codeDescription.add("[الو 14]\n" + "سعر الدقيقة لكل الشبكات: 14 قرش\n" + "سعر الميجابايت: 14 قرش\n" + "سعر الرسالة لكل الشبكات: 14 قرش\n" + "سعر الدقيقة للرقم المفضل: 10 قرش");    codeCategory.add("انظمه الو");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#0#5132#");          codeDescription.add("[الو اليومي]\n" + "(سعر الباقة) 1.5 جنيه\n" + "(عدد وحدات) 60 وحدة\n" + "(صلاحية الباقة) 24 ساعة\n" + "(عدد تجديد الباقة) لا يوجد عدد محدد لتجديد الباقة\n" + "(سعر دقيقة اورنچ داخل الباقة) 1 وحدة\n" + "(سعر الدقيقة للشبكات الأخرى داخل الباقة) 5 وحدات\n" + "(سعر الرسالة لاورنچ داخل الباقة) 1 وحدة\n" + "(سعر الرسالة للشبكات الأخرى داخل الباقة) 5 وحدات\n" + "(سعر الميجا داخل الباقة) 1 وحدة\n" + "(سعر الدقيقة و الرسالة لكل الشبكات خارج الباقة و الميجا) 14 قرش\n" + "(تجديد الباقة)عند وجود ثمن الباقة، تجدد الباقة تلقائيا مع اول مكالمة أو رسالة أو استخدام ميجابايتس\n" + "(عدد ارقام اورنچ المفضلة) 3 ارقام\n" + "(سعر دقيقة اورنچ داخل الباقة للأرقام المفضلة) نص وحدة بدل 1 وحدة");    codeCategory.add("انظمه الو");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#0#5133#");          codeDescription.add("[الو الاسبوعي]\n" + "(سعر الباقة) 7 جنيه\n" + "(عدد الوحدات) 300 وحدة\n" + "(صلاحية الباقة) 7 ايام\n" + "(عدد تجديد الباقة) لا يوجد عدد محدد لتجديد الباقة\n" + "(سعر دقيقة اورنچ داخل الباقة) 1 وحدة\n" + "(سعر الدقيقة للشبكات الأخرى داخل الباقة) 5 وحدات\n" + "(سعر الرسالة لاورنچ داخل الباقة) 1 وحدة\n" + "(سعر الرسالة للشبكات الأخرى داخل الباقة) 5 وحدات\n" + "(سعر الميجا داخل الباقة) 1 وحدة\n" + "(سعر الدقيقة و الرسالة لكل الشبكات خارج الباقة و الميجا) 14 قرش\n" + "(تجديد الباقة)عند وجود ثمن الباقة، تجدد الباقة تلقائيا مع اول مكالمة أو رسالة أو استخدام ميجابايتس\n" + "(عدد ارقام اورنچ المفضلة) 3 ارقام\n" + "(سعر دقيقة اورنچ داخل الباقة للأرقام المفضلة) نصف وحدة بدل 1 وحدة");    codeCategory.add("انظمه الو");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");

         //       codeNumber.add("#18#1#");          codeDescription.add("لمعرفه رصيدك وكم المتبقي من الباقه المستخدمه");    codeCategory.add("اكواد مهمه");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");codeNumber.add("#18#2#");          codeDescription.add("لتجديد اي باقه");    codeCategory.add("اكواد مهمه");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
           //     codeNumber.add("#18#3#");          codeDescription.add("لللاشتراك في باقات اضافيه حتي تجديد الباقه");    codeCategory.add("اكواد مهمه");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");


                codeNumber.add("https://shop.orange.eg/ar/tariff-plans/elking");    codeDescription.add("لمزيد من التفاصيل حول أنظمة الكينج");    codeCategory.add( "المصدر الرئيسي");    separateCategories.add("URLSource");    determineAction.add("ACTION_VIEW");
                codeNumber.add("https://shop.orange.eg/ar/tariff-plans/control");    codeDescription.add("لمزيد من التفاصيل حول باقات كنترول");    codeCategory.add( "المصدر الرئيسي");    separateCategories.add("URLSource");    determineAction.add("ACTION_VIEW");
                codeNumber.add("https://shop.orange.eg/ar/tariff-plans/alo");    codeDescription.add("لمزيد من التفاصيل حول باقات الو");    codeCategory.add( "المصدر الرئيسي");    separateCategories.add("URLSource");    determineAction.add("ACTION_VIEW");

                break;

            case "ViewModelCodesDataEntertainmentBundles":
                codeNumber.add("#78#");          codeDescription.add("حصريا مع خدمة المطبخ من اورنچ تابع وصفات الاكل المختلفة و فرصة تكسب جنيهات دهب\n" + "عند الاشتراك ستحصل على 10 دقائق مجانية صالحة حتى نهاية اليوم التالي ؛ ثم استمتع بوصفات الاكل المختلفة مع غادة التالي\n" + "لإلغاء الاشتراك أبعت \"الغاء\" او \" unsub \" ل 7819 مجانا");    codeCategory.add("خدمة المطبخ");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#657#");          codeDescription.add("حصريا مع خدمة الفرسان الدينية من اورنچ ..اسمع اناشيد يومية من الفنان هاني شاكر عن الأنبياء و الصحابة.\n" + "و حاول تعرف مين النبي او الصحابي علشان تكسب 5000 جنيه يوميا.\n" + "عند الاشتراك ستحصل على 10 دقائق مجانية صالحة حتى نهاية اليوم التالي ؛ ثم استمتع بالحلقات الدينية اليومية بصوت هاني شاكر عبر https://elforsan.net/ و سؤال يومي في نهاية كل حلقة.\n" + "ارسل الإجابة الصحيحة على الرقم 6122 لفرصة الفوز ب 5000 جنيه يوميا\n" + "و لإلغاء الاشتراك أبعت \"الغاء\" ل6122 مجانا");    codeCategory.add("خدمة الفرسان الدينية");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#900#");          codeDescription.add("مع خدمة حريف غنا هتستمتع بأخبار و معلومات يومية تساعدك علي تحسين صوتك و هتقدر تسجل فيديو و تنزله و انت بتغني عليhttp://hareefghona.com و فرصة تكسب 1,000,000 جنيه لإلغاء الاشتراك أبعت \"الغاء\" ل 2426 مجانا\n" + "السعر: 2 جنيه/ يوميا");    codeCategory.add("حريف غنا");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#55#");          codeDescription.add("حصريا لعملاء Orange خصية لمشاهده احدث البرامج و الافلام و المسلسلات من خلال تطبيق Orange TV حمل التطبيق و تابع كل الافلام و المسلسلات الي بتحبها في اي وقت و في اي مكان.\n" + "استمتع بالمحتوي العالمي علي Orange TV plus و بخاصيات اكتر.\n" + "السعر: 1.5ج/يوم");    codeCategory.add("Orange TV Plus");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#93#");          codeDescription.add("اشترك في خدمة الدوري واعرف كل اخبار الدوري مع الكابتن احمد حسن وممكن تكسب IPhone 12 . اشترك في خدمة الدوري عشان تعرف كل المعلومات الصح عن الدوري مع الكابتن احمد حسن. ممكن كمان تجاوب علي اسئلة المسابقة عشان تجمع نقط ويبقي عندك فرصة تكسب IPhone 12.\n" + "\n" + "السعر: 2 جنيه يوميا\n" + "متاح ل: لكل عملاء Orange\n" + "للإلغاء: ابعت “unsub” او \"الغاء\" ل1019");    codeCategory.add("خدمة الدوري");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#59#");          codeDescription.add("اشترك في خدمة حريف كورة وعيش اجواء الاحتراف في نادي اوروبي او اختبر معلواتك الكروية وممكن تكسب 500,000 جنيه\n" + "تقدر من خلال خدمة حريف كورة تشوف فيديوهات لمجموعة من حريفة الكورة المصريين او مجموعة من فيديوهات للجيل الذهبي جدو, محمد شوقي, عمرو ذكي, ابراهيم سعيد, احمد عيد عبد الملك وشريف عبد الفضيل. انت كمان ممكن ترفع فيديوهاتك وانت بتلعب وتورينا مهراتك علي البوابة الالكترونية لحريف كورة. حريف كورة كمان هتخليك تختبر معلوماتك الكروية عشان يبقي عندك فرصة تكسب جوائز نقدية.\n" + "الرسوم: 2 جنيه يوميا\n" + "لالغاء الاشتراك في الخدمه ارسل \" الغاء \" لرقم 5420");    codeCategory.add("حريف كورة");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("9988");          codeDescription.add("الآن مع باقة غنيلى من اورنچ وروتانا، يمكنك تحميل أغاني، رنات، وكليبات والاستمتاع بكول تون على موبايلك و هيوصلك اخبار نجوم روتانا كل يوم. \n" + "للإلغاء: ارسل رسالة الغاء لـ9988\n" + "السعر: سعر الباقة 34 قرش يوميا شاملة الستريم و الداونلود و تضم 10 محتويات.\n" + "سعر الدقيقة لـ9988 5 قروش.");    codeCategory.add("غنيلي");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_CALL");
                codeNumber.add("#37#");          codeDescription.add("حصريا لعملاء اورنچ اشترك في الخدمة الترفيهية لو موهوب وعندك فرصه تشارك و تعرض موهبتك. أول 3 ايام ببلاش بعد كده ب1.5جنيه/يوم. متضيعش فرصه انك تبقي نجم مع اورنچ!\n" + "للإغلاء : ابعت الغاء ل 7613");    codeCategory.add("Mawhoob");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("8000");          codeDescription.add("دليلك الشخصي 24 ساعة في اليوم، 7 ايام في الأسبوع من خلال اورنچ 8000 مركز اتصالات كامل يعمل به مندوبون متخصصون لموافاتك بالمعلومات الفورية وأرقام التليفون والكثير على التليفون أو عن طريق الرسائل القصيرة. مع اورنچ 8000 يمكنك الحصول على مساعدك الشخصي الذي ينوب عنك في إرسال رسالة قصيرة أو فاكس كما يمكنه إمدادك بالعروض الخاصة\n" + "\n" + "الخدمات الحكومية\n" + " احنا هنجددلك البطاقة و الرخصة القيادة و هنخلصلك كل مشاوير الحكومية\n" + "\n" + "خدمات السينما الحصرية\n" + "فقط مع اورنچ 8000 تقدر تعرف احدث الافلام فى السينمات.\n" + "\n" + "أماكن الخروج والمطاعم\n" + "عشان تعرف أحدث و أرقى المطاعم و كمان ممكن تستفسر عن أى مكان داخل أو خارج مصر.\n" + "\n" + "السفر والسياحة\n" + "مصر هي موطن للآثار الثقافية في التاريخ القديم والحديث. مع اورنچ 8000 سوف تتعرف على أفضل الأماكن السياحية.\n" + "\n" + "التسوق\n" + "مع زيادة الأسعار والتغير السريع في المناخ الاقتصادي الحالي، عشان تعرف أين تتسوق بأقل أسعار و لا تفوت أي عرض .\n" + "\n" + "السيارات\n" + "من لامبورغيني لمازيراتي لشركة فيات، سوف تحصل على كل المعلومات عن أفضل وكلاء السيارات في كل مصر. لمعرفة المزيد أو حجز موعد صيانة سيارتك.\n" + "\n" + "خدمات طبية\n" + "اورنچ 8000 بتقدم لك كل المعلومات عن المستشفيات والعيادات وشركات التأمين الصحي للحفاظ على صحتك.\n" + "\n" + "مجال الأعمال\n" + "إذا كنت من أصحاب الأعمال التجارية، لا تتردد في استخدام 8000 لتعرف كل المعلومات المتعلقة بعناوين وتليفونات أي شركة.\n" + "\n" + "التعليم\n" + "كل ما تحتاجه لمعرفة معلومات وبيانات عن المدارس أو الجامعات بمجرد مكالمة واحدة الأن.\n" + "\n" + "معلومات دينية\n" + "من المساجد القديمة إلى الكنائس المقدسة، إن مصر دولة غنية بالثقافة الدينية. مع اورنچ 8000 يمكنك أن تعرف كل شيء عن أين وماذا ومتى ترى كل ذلك وكمان اوقات الصلاة اليومية.\n" + "\n" + "الرياضة\n" + "هل أنت من عشاق الرياضة؟ الآن يمكنك متابعة كل نتائج وجداول وأخبار المسابقات في كل الألعاب الرياضية من جميع أنحاء العالم.");    codeCategory.add("اورنچ 8000");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_CALL");
                codeNumber.add("9999");          codeDescription.add("كل اللي هيكلمك هيسمع صوت الاذان في مواعيد الصلاة فقط.\n" + "خدمة الاذان متاحة لمدة 30 يوم و تجدد تلقائيا\n" + "لإلغاء الإشتراك كلم 9999 ب 0.50 جنيه للدقيقة ثم اضغط 4\n" + "السعر: جنيه واحد فقط في الشهر.");    codeCategory.add("خدمة الاّذان");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_CALL");
                codeNumber.add("9999");          codeDescription.add("خدمة الدعاء مع اورنچ, هتسمّع كُل اللي يكلمك ادعيه الصباح و المساء و لو انت عندك كول تون و اشتركت في الخدمة, الخدمه هشتغل بدل الكول تون في اوقات الادعيه.\n" + "لإلغاء الإشتراك كلم 9999 ب 0.50 جنيه للدقيقة ثم اضغط 4\n" + "السعر:جنيه واحد فقط في الشهر.");    codeCategory.add("خدمة الدعاء");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_CALL");


                codeNumber.add("https://www.orange.eg/ar/Entertainment/");    codeDescription.add("لمزيد من التفاصيل حول باقات ترفيه");    codeCategory.add( "المصدر الرئيسي");    separateCategories.add("URLSource");    determineAction.add("ACTION_VIEW");

                break;

            case "ViewModelCodesDataCallCenter":
                codeNumber.add("110");    codeDescription.add("اتصال بخدمه العملاء من خط اورانخ");    codeCategory.add( "ارقام خدمه العملاء");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_CALL");
                codeNumber.add("16110");    codeDescription.add( "الخط الساخن لخدمه عملاء اورانج");    codeCategory.add( "ارقام خدمه العملاء");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_CALL");
                codeNumber.add("16333");    codeDescription.add("خدمه عملاء اورانج خط ساخن اخر");    codeCategory.add("ارقام خدمه العملاء");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_CALL");
                codeNumber.add("01223202020");    codeDescription.add( "الاتصال بخدمه العملاء من خارج مصر");    codeCategory.add("ارقام خدمه العملاء");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_CALL");
                codeNumber.add("400");    codeDescription.add( "اخدماتك الشخصية: لو عايز كشف حساب او تعرف رمز الـ Puk و كمان العروض الجديدة و ازاي تسدد فاتورتك\n" + "\n" + "عايز تعرف عروضنا الجديدة و التخفيضات و الخدمات\n" + "\n" + "لو خطك اتكلم و اتحكم تفدر تعرف تشحن ازاي و تراجع حسابك و كمان تجدد خطك لو بريمو\n");    codeCategory.add("ارقام خدمه العملاء");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_CALL");
                codeNumber.add("2000");    codeDescription.add( "لو انت first class ده رقم خدمه العملاء اللى عملناه علشانك");    codeCategory.add("ارقام خدمه العملاء");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_CALL");
                codeNumber.add("555");    codeDescription.add( "عايز حد يجيلك يحصل فاتورتك ديه خدمة First service");    codeCategory.add("ارقام خدمه العملاء");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_CALL");
                codeNumber.add("0235362326");    codeDescription.add("الو حساب جديد كلمنا من خط الأرضي (من 9ص إلي 5م)");    codeCategory.add( "ارقام خدمه العملاء");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_CALL");
                codeNumber.add("https://www.orange.eg/ar/help/short-numbers");    codeDescription.add("لمزيد من التفاصيل حول ارقام خدمه العملاء");    codeCategory.add( "المصدر الرئيسي");    separateCategories.add("URLSource");    determineAction.add("ACTION_VIEW");
                break;

            case "ViewModelCodesDataOthers":
                codeNumber.add("#119#1#");          codeDescription.add("لاستعلام عن رقم الخط");    codeCategory.add("استعلام");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#119#2#");          codeDescription.add("للاستعلام عن الرقم السري");    codeCategory.add("استعلام");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#100#57#");          codeDescription.add("لمعرفه معلومات عن خطك (PUK CODE)");    codeCategory.add("استعلام");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#100#56#");          codeDescription.add("لمعرفه نظام باقتك الحاليه (اسم الباقه الحاليه)");    codeCategory.add("استعلام");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("9999");          codeDescription.add("للاشتراك او الغاء الكول تون");    codeCategory.add("كول تون");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_CALL");
                codeNumber.add("#100#322#");          codeDescription.add("للاشتراك في خدمه البلوك \n" + "الباقه اليوميه 0.30 جنيه\n" + "الباقه الشهريه 5 جنيه");    codeCategory.add("خدمه البلوك");    separateCategories.add("SecondCategory");    determineAction.add("ACTION_DIAL");
                codeNumber.add("#100#582#");          codeDescription.add("لتغير اللغه");    codeCategory.add("خدمه تغير اللغه");    separateCategories.add("FirstCategory");    determineAction.add("ACTION_DIAL");
                break;


        }

        setCodeNumber(codeNumber);
        setCodeDescription(codeDescription);
        setCodeCategory(codeCategory);
        setSeparateCategories(separateCategories);
        setDetermineAction(determineAction);
    }

}
